#springdoc:
#  api-docs:
#    path: /v3/api-docs
#  swagger-ui:
#    path: /swagger-ui.html
  # ⚠️ নিচের info কাজ করবে না YAML-এ — এইটা Java Bean দিয়ে করতে হবে
  # info:
  #   title: My Custom API
  #   description: This is a custom description for my API
  #   version: 1.0.0

server:
  port: 9091

spring:
  application:
    name: Spring-Boot-Security-01

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:spring_security}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Pgsql#321}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  jwt:
    secret: "this-is-a-very-secure-long-secret-key-for-hs256"
    expiration: 3600000 # in milliseconds (1 hour)
